#spring:
#  redis:
#    lettuce:
#      pool:
#        max-active: 8
#        min-idle: 0
#        max-wait: 2
#        max-idle: 8
##    cluster:
##      nodes: 173.17.202.1:6379,172.17.202.2:6379,172.17.202.3:6379
#    port: 6379
#    password: